@startuml
start
    : Ставим сковороду на огонь;
    : Ждём, когда сковородка нагреется;
if (Проверяем, нагрелась ли сковородка?) then(да)
else (Нет)
    :Ждём нагрева;
endif
    : Выливаем масло и прогреваем его;
    : Разбиваем по одному яйцу;
    : Солим только белки;
if(Готовим  10 минут. Проверяем время, прошло ли 10 минут?) then (да)
else (нет)
    : Выжидаем время;
endif
    : Проверяем состояние белка;
if (Белок полужидкий?) then (да)

else (Нет)
    : Продолжаем готовить;
endif
    : Выключаем огонь;
    : Подготавливаем тарелку и кулинарную лопатку;
    : Достаём яичницу и кладём на тарелку;
    : Посыпаем специи и кетчупа;
    : Подготавливаем вилку и ножик;
    : Нарезаем хлеб;
if (Проверяем, горячая ли вода в чайнике?) then (да)

else (нет)
    : Поставить чайник кипятить;
    : Вскипятитить чайник;

endif
    : Положить пакетик чая в кружку;
    : Налить в кружку горячую воду;
    : Подождать 2-3 минутки;
    :Чай готов;
    :                               Приступаем к еде.


stop
@enduml
