@startuml
start
    : Ставим сковороду на огонь;
    : Ждём, когда сковородка нагреется;
if (Проверяем, нагрелась ли сковородка?) then(да)
else (Нет)
    :Ждём нагрева;
endif
    : Выливаем масло и прогреваем его;
    : Разбиваем по одному яйцу;
    : Солим только белки;
if(Готовим  10 минут. Проверяем время, прошло ли 10 минут?) then (да)
else (нет)
    : Выжидаем время;
endif
    : Проверяем состояние белка;
if (Белок полужидкий?) then (да)

else (Нет)
    : Продолжаем готовить;
endif
    : Выключаем огонь;
    : Подготавливаем тарелку и кулинарную лопатку;
    : Достаём яичницу и кладём на тарелку;
    : Посыпаем специи и кетчупа;
    : Подготавливаем вилку и ножик;
    : Нарезаем хлебушка....ням-ням));
if (Проверяем, горячая ли вода в чайнике?) then (да)

else (нет)
    : Поставить чайник капитить;
    : Скапитить чайник;

endif
    : Положить пакетик чая в кружку;
    : Налить в кружку горячую воду;
    : Подождать 2-3 минутки;
    :Чай готов;
    :                               Садимся за стол и кушаем.
    Приятного аппетита  и с наступающим Вас Новым Годом!!!;
    :Увидимся в следующем году!!!;

stop
@enduml
